In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [4]:
baseline = pd.read_csv('../../data/enhanced_baseline_model_results.csv')
baseline.head()

,lr_frp,lr_predict_frp,lr_frp_difference,lr_R2,lr_RMSE,lr_MAE,xgb_frp,xgb_predict_frp,xgb_frp_difference,xgb_R2,xgb_RMSE,xgb_MAE,gb_frp,gb_predict_frp,gb_frp_difference,gb_R2,gb_RMSE,gb_MAE
0,4.09,13.473736,-9.383736,0.151459,19.154463,7.959108,4.09,7.620114,-3.530114,0.411874,15.946634,5.561124,4.09,7.671623,-3.581623,0.412002,15.944896,5.571684
1,24.22,18.788881,5.431119,0.151459,19.154463,7.959108,24.22,19.259491,4.960509,0.411874,15.946634,5.561124,24.22,19.064085,5.155915,0.412002,15.944896,5.571684
2,11.06,11.026460,0.033540,0.151459,19.154463,7.959108,11.06,11.808919,-0.748919,0.411874,15.946634,5.561124,11.06,11.901417,-0.841417,0.412002,15.944896,5.571684
3,7.04,19.721451,-12.681451,0.151459,19.154463,7.959108,7.04,5.201190,1.838810,0.411874,15.946634,5.561124,7.04,5.209907,1.830092,0.412002,15.944896,5.571684
4,4.38,2.345195,2.034805,0.151459,19.154463,7.959108,4.38,5.752706,-1.372706,0.411874,15.946634,5.561124,4.38,5.853444,-1.473444,0.412002,15.944896,5.571684

In [5]:
model_results = pd.read_csv('../../data/model_results.csv')
model_results.head()

,model_name,is_grid_search,used_pca,pca_components,parameters,rmse_original,mae_original,r2_original,rmse_log,mae_log,r2_log
0,lr,False,False,NaN,"{""memory"": ""None"", ""model"": ""LinearRegression(...",19.366145,5.608732,0.132601,0.596161,0.415207,0.524785
1,lr_gs,True,True,10.0,"{""pca__n_components"": ""10"", ""ridge__alpha"": ""1...",19.492246,5.771453,0.121268,0.612160,0.438251,0.498937
2,xgb,False,False,NaN,"{""base_score"": ""None"", ""booster"": ""None"", ""cal...",16.504836,4.909467,0.369979,0.512286,0.360830,0.649097
3,xgb_gs,True,True,10.0,"{""pca__n_components"": ""10"", ""xgb__learning_rat...",16.791109,5.021265,0.347934,0.526750,0.371983,0.629002
4,gb,False,False,NaN,"{""alpha"": ""0.9"", ""ccp_alpha"": ""0.0"", ""criterio...",16.832046,5.024001,0.344751,0.526499,0.370727,0.629355

In [6]:
model_predictions = pd.read_csv('../../data/model_predictions.csv')
model_predictions.head()

,enhanced_lr_frp,enhanced_lr_predict_frp,enhanced_lr_frp_difference,enhanced_lr_R2,enhanced_lr_RMSE,enhanced_lr_MSE,enhanced_lr_MAE,enhanced_lr_gs_frp,enhanced_lr_gs_predict_frp,enhanced_lr_gs_frp_difference,...,enhanced_xgb_gs_RMSE,enhanced_xgb_gs_MSE,enhanced_xgb_gs_MAE,enhanced_gb_frp,enhanced_gb_predict_frp,enhanced_gb_frp_difference,enhanced_gb_R2,enhanced_gb_RMSE,enhanced_gb_MSE,enhanced_gb_MAE
0,4.09,7.756601,-3.666601,0.132601,19.366145,375.047563,5.608732,4.09,8.254870,-4.164870,...,16.791109,281.941339,5.021265,4.09,6.782509,-2.692509,0.344751,16.832046,283.317785,5.024001
1,24.22,12.463449,11.756551,0.132601,19.366145,375.047563,5.608732,24.22,11.505360,12.714640,...,16.791109,281.941339,5.021265,24.22,15.114064,9.105936,0.344751,16.832046,283.317785,5.024001
2,11.06,9.260346,1.799654,0.132601,19.366145,375.047563,5.608732,11.06,8.624887,2.435113,...,16.791109,281.941339,5.021265,11.06,9.319817,1.740183,0.344751,16.832046,283.317785,5.024001
3,7.04,9.612519,-2.572519,0.132601,19.366145,375.047563,5.608732,7.04,8.858897,-1.818897,...,16.791109,281.941339,5.021265,7.04,6.228032,0.811968,0.344751,16.832046,283.317785,5.024001
4,4.38,5.062916,-0.682916,0.132601,19.366145,375.047563,5.608732,4.38,5.528828,-1.148828,...,16.791109,281.941339,5.021265,4.38,5.567081,-1.187081,0.344751,16.832046,283.317785,5.024001

In [7]:
model_predictions.columns

Index(['enhanced_lr_frp', 'enhanced_lr_predict_frp',
       'enhanced_lr_frp_difference', 'enhanced_lr_R2', 'enhanced_lr_RMSE',
       'enhanced_lr_MSE', 'enhanced_lr_MAE', 'enhanced_lr_gs_frp',
       'enhanced_lr_gs_predict_frp', 'enhanced_lr_gs_frp_difference',
       'enhanced_lr_gs_R2', 'enhanced_lr_gs_RMSE', 'enhanced_lr_gs_MSE',
       'enhanced_lr_gs_MAE', 'enhanced_xgb_frp', 'enhanced_xgb_predict_frp',
       'enhanced_xgb_frp_difference', 'enhanced_xgb_R2', 'enhanced_xgb_RMSE',
       'enhanced_xgb_MSE', 'enhanced_xgb_MAE', 'enhanced_xgb_gs_frp',
       'enhanced_xgb_gs_predict_frp', 'enhanced_xgb_gs_frp_difference',
       'enhanced_xgb_gs_R2', 'enhanced_xgb_gs_RMSE', 'enhanced_xgb_gs_MSE',
       'enhanced_xgb_gs_MAE', 'enhanced_gb_frp', 'enhanced_gb_predict_frp',
       'enhanced_gb_frp_difference', 'enhanced_gb_R2', 'enhanced_gb_RMSE',
       'enhanced_gb_MSE', 'enhanced_gb_MAE'],
      dtype='object')

In [9]:
model_detailed_predictions = pd.read_csv('../../data/model_predictions_detailed.csv')
model_detailed_predictions.head()

,enhanced_lr_frp,enhanced_lr_predict_frp,enhanced_lr_frp_difference,enhanced_lr_R2,enhanced_lr_RMSE,enhanced_lr_MSE,enhanced_lr_MAE,enhanced_lr_abs_error,enhanced_lr_percent_error,enhanced_lr_log_frp,...,enhanced_gb_predict_frp,enhanced_gb_frp_difference,enhanced_gb_R2,enhanced_gb_RMSE,enhanced_gb_MSE,enhanced_gb_MAE,enhanced_gb_abs_error,enhanced_gb_percent_error,enhanced_gb_log_frp,enhanced_gb_log_predict_frp
0,4.09,7.756601,-3.666601,0.132601,19.366145,375.047563,5.608732,3.666601,89.647956,1.627278,...,6.782509,-2.692509,0.344751,16.832046,283.317785,5.024001,2.692509,65.831523,1.627278,2.051879
1,24.22,12.463449,11.756551,0.132601,19.366145,375.047563,5.608732,11.756551,48.540673,3.227637,...,15.114064,9.105936,0.344751,16.832046,283.317785,5.024001,9.105936,37.596763,3.227637,2.779692
2,11.06,9.260346,1.799654,0.132601,19.366145,375.047563,5.608732,1.799654,16.271740,2.489894,...,9.319817,1.740183,0.344751,16.832046,283.317785,5.024001,1.740183,15.734023,2.489894,2.334066
3,7.04,9.612519,-2.572519,0.132601,19.366145,375.047563,5.608732,2.572519,36.541462,2.084429,...,6.228032,0.811968,0.344751,16.832046,283.317785,5.024001,0.811968,11.533642,2.084429,1.977967
4,4.38,5.062916,-0.682916,0.132601,19.366145,375.047563,5.608732,0.682916,15.591699,1.682688,...,5.567081,-1.187081,0.344751,16.832046,283.317785,5.024001,1.187081,27.102307,1.682688,1.882069

In [12]:
model_detailed_predictions.columns

Index(['enhanced_lr_frp', 'enhanced_lr_predict_frp',
       'enhanced_lr_frp_difference', 'enhanced_lr_R2', 'enhanced_lr_RMSE',
       'enhanced_lr_MSE', 'enhanced_lr_MAE', 'enhanced_lr_abs_error',
       'enhanced_lr_percent_error', 'enhanced_lr_log_frp',
       'enhanced_lr_log_predict_frp', 'enhanced_lr_gs_frp',
       'enhanced_lr_gs_predict_frp', 'enhanced_lr_gs_frp_difference',
       'enhanced_lr_gs_R2', 'enhanced_lr_gs_RMSE', 'enhanced_lr_gs_MSE',
       'enhanced_lr_gs_MAE', 'enhanced_lr_gs_abs_error',
       'enhanced_lr_gs_percent_error', 'enhanced_lr_gs_log_frp',
       'enhanced_lr_gs_log_predict_frp', 'enhanced_xgb_frp',
       'enhanced_xgb_predict_frp', 'enhanced_xgb_frp_difference',
       'enhanced_xgb_R2', 'enhanced_xgb_RMSE', 'enhanced_xgb_MSE',
       'enhanced_xgb_MAE', 'enhanced_xgb_abs_error',
       'enhanced_xgb_percent_error', 'enhanced_xgb_log_frp',
       'enhanced_xgb_log_predict_frp', 'enhanced_xgb_gs_frp',
       'enhanced_xgb_gs_predict_frp', 'enhanced_xgb_gs_frp_difference',
       'enhanced_xgb_gs_R2', 'enhanced_xgb_gs_RMSE', 'enhanced_xgb_gs_MSE',
       'enhanced_xgb_gs_MAE', 'enhanced_xgb_gs_abs_error',
       'enhanced_xgb_gs_percent_error', 'enhanced_xgb_gs_log_frp',
       'enhanced_xgb_gs_log_predict_frp', 'enhanced_gb_frp',
       'enhanced_gb_predict_frp', 'enhanced_gb_frp_difference',
       'enhanced_gb_R2', 'enhanced_gb_RMSE', 'enhanced_gb_MSE',
       'enhanced_gb_MAE', 'enhanced_gb_abs_error', 'enhanced_gb_percent_error',
       'enhanced_gb_log_frp', 'enhanced_gb_log_predict_frp'],
      dtype='object')